#!/bin/sh
set -eu

bot_name=${GIT_COMMIT_AS_BOT_NAME:-shiny-code-bot}
bot_email=${GIT_COMMIT_AS_BOT_EMAIL:-chris@shinycomputers.com}
git_bin=${GIT_COMMIT_AS_BOT_GIT:-git}

if [ "$#" -eq 0 ]; then
	echo "usage: git-commit-as-bot <git commit args...>" >&2
	exit 2
fi

GIT_AUTHOR_NAME=$bot_name \
	GIT_AUTHOR_EMAIL=$bot_email \
	GIT_COMMITTER_NAME=$bot_name \
	GIT_COMMITTER_EMAIL=$bot_email \
	"$git_bin" commit "$@"
