#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = ["tomlkit==0.15.1"]
# ///
"""Render both hosts' global instructions from one catalog source bundle.

Preview by default. --write preserves each changed destination in a sibling
backup before replacing it. Private host instructions stay in the ignored
source .local/global-instructions.md, shared by both outputs.
If the local source is missing, restore it in the maintained runtime checkout
and preview there before writing. To intentionally remove private instructions,
use an empty .local/global-instructions.md there and preview before writing.
Writing changes to existing instructions without the local source is refused
unless --allow-missing-local is given; that override drops private instructions.
"""

from __future__ import annotations

import argparse
import copy
import datetime as dt
import difflib
import hashlib
import json
import os
import re
import shlex
import sys
import tempfile
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HEADER = "<!-- Generated by codex-skills/scripts/sync-global-instructions.py; edit the catalog source. -->"
HOOK_LABEL = "codex-skills command policies"
MISSING_LOCAL_RECOVERY = (
    "Restore the private source in the maintained runtime checkout and preview there before writing. "
    "To intentionally remove private instructions, use an empty local source there and preview before writing "
    "(.local/global-instructions.md by default, or the --local-source path). "
    "The explicit --allow-missing-local override overwrites existing instruction files and drops any private instructions."
)
HOOK_TRUST_NOTICE = "Trust is Codex-managed and unchanged. Migrated, new, or changed hooks may be skipped until reviewed through Codex /hooks; review them before relying on enforcement. Disabled choices are not copied: keep previously disabled hooks off when reviewing migrated definitions."


class HookOutputs(dict[Path, str]):
    def __init__(self, contents: dict[Path, str], previous: dict[Path, bytes | None], migrated_events: dict[str, int], disabled_migrated_handlers: list[dict]):
        super().__init__(contents)
        self.previous = previous
        self.migrated_events = migrated_events
        self.disabled_migrated_handlers = disabled_migrated_handlers


def render(source: Path, local_source: Path) -> str:
    sections = [HEADER, source.read_text().strip()]
    if local_source.exists():
        sections.append(local_source.read_text().strip())
    return "\n\n".join(section for section in sections if section) + "\n"


def render_codex_hook(destination: Path, catalog: Path = ROOT, *, include_session_start: bool = False, alerts_only: bool = False, config: dict | None = None) -> str:
    """Bind catalog declarations, preserving unrelated hooks and host trust."""
    if destination.is_symlink() or (destination.exists() and not destination.is_file()):
        raise ValueError(f"Refusing a symlink or non-file destination: {destination}")
    if config is None:
        config = json.loads(destination.read_text()) if destination.exists() else {}
    return render_codex_hook_content(config, destination, catalog, include_session_start=include_session_start, alerts_only=alerts_only)


def render_codex_hook_content(config: dict, destination: Path, catalog: Path = ROOT, *, include_session_start: bool = False, alerts_only: bool = False) -> str:
    """Render already-read definitions without writing or resolving the destination."""
    config = copy.deepcopy(config)
    if not isinstance(config, dict) or not isinstance(config.get("hooks", {}), dict):
        raise ValueError(f"Invalid hooks configuration: {destination}")
    hooks = config.setdefault("hooks", {})
    source = json.loads((catalog / "hooks" / "hooks.json").read_text())["hooks"]
    events = ["Stop", "Interrupt"] if alerts_only else ["PreToolUse", "Stop", "Interrupt", "SessionStart"]
    for event in events:
        existing = hooks.get(event, [])
        if not isinstance(existing, list):
            raise ValueError(f"Invalid {event} configuration: {destination}")
        # Claude has no Interrupt event; Codex binds its native event to the
        # same alert declaration. Keep one maintained command source.
        declarations = copy.deepcopy(source["Stop" if event == "Interrupt" else event]) if event != "SessionStart" or include_session_start else []
        label = {"PreToolUse": HOOK_LABEL, "SessionStart": "codex-skills session start",
                 "Stop": "codex-skills stop alert", "Interrupt": "codex-skills interrupt alert"}[event]
        if event == "SessionStart":
            declarations = [group for group in declarations if group.get("matcher") != "compact"]
        for group in declarations:
            for handler in group["hooks"]:
                environment = ["env", f"CLAUDE_PLUGIN_ROOT={catalog}"]
                if event in ("Stop", "Interrupt"):
                    environment.append("CODEX_SKILLS_HARNESS=codex")
                handler["command"] = shlex.join([*environment, "sh", "-c", handler["command"]])
                handler["statusMessage"] = label
        if event in ("Stop", "Interrupt"):
            positions = [index for index, group in enumerate(existing) if (
                isinstance(group, dict) and isinstance(group.get("hooks"), list) and len(group["hooks"]) == 1
                and isinstance(group["hooks"][0], dict) and group["hooks"][0].get("statusMessage") == label
            )]
            if positions and len(positions) != len(declarations):
                raise ValueError(f"Conflicting catalog {event} entries; inspect {destination} before rerunning. Install with --skip-codex-hooks, or synchronize instructions without --codex-hook, to preserve hooks and keep working")
        def managed(group):
            return (isinstance(group, dict) and isinstance(group.get("hooks"), list) and len(group["hooks"]) == 1
                    and isinstance(group["hooks"][0], dict) and group["hooks"][0].get("statusMessage") == label)
        updated = []
        inserted = False
        for group in existing:
            if managed(group):
                if not inserted:
                    updated.extend(declarations)
                    inserted = True
            else:
                updated.append(group)
        if not inserted:
            updated.extend(declarations)
        if updated or event in hooks:
            hooks[event] = updated
    return json.dumps(config, indent=2) + "\n"


def safe_content(path: Path) -> str:
    if path.is_symlink() or (path.exists() and not path.is_file()):
        raise ValueError(f"Refusing a symlink or non-file destination: {path}. Install with --skip-codex-hooks, or synchronize instructions without --codex-hook, to preserve existing hooks while continuing setup.")
    return path.read_bytes().decode() if path.exists() else ""


def existing_session_hook(groups: list, catalog: Path) -> bool:
    found = False
    for group in groups:
        handlers = group.get("hooks", []) if isinstance(group, dict) else []
        if not isinstance(handlers, list):
            raise ValueError("Invalid SessionStart hook handlers; inspect hooks.json or config.toml before rerunning")
        for handler in handlers:
            if not isinstance(handler, dict):
                continue
            command = handler.get("command", "")
            if not isinstance(command, str) or "direction_check_hook.py" not in command:
                continue
            if handler.get("statusMessage") == "codex-skills session start":
                continue  # Regenerated by render_codex_hook.
            tokens = shlex.split(command)
            plugin_root = next((token.partition("=")[2] for token in tokens if token.startswith("CLAUDE_PLUGIN_ROOT=")), os.environ.get("CLAUDE_PLUGIN_ROOT", ""))
            candidates = list(tokens)
            for index, token in enumerate(tokens):
                if Path(token).name in ("sh", "bash", "zsh", "fish"):
                    for flag_index in range(index + 1, len(tokens) - 1):
                        flag = tokens[flag_index]
                        if not flag.startswith("-"):
                            if tokens[flag_index - 1] in ("-o", "+o", "--rcfile", "--init-file"):
                                continue
                            break
                        if flag == "-c" or (not flag.startswith("--") and "c" in flag[1:]):
                            candidates.extend(shlex.split(tokens[flag_index + 1]))
                            break
            candidates = [token.replace("${CLAUDE_PLUGIN_ROOT}", plugin_root).replace("$CLAUDE_PLUGIN_ROOT", plugin_root) for token in candidates]
            if "--skills-only" in candidates:
                continue  # A compact-only check does not provide startup reminders.
            paths = [Path(os.path.expandvars(token)).expanduser() for token in candidates]
            if not any(path.is_absolute() and path.resolve() == (catalog / "hooks" / "direction_check_hook.py").resolve() for path in paths):
                raise ValueError("Existing session hook preserved: direction_check_hook.py does not unambiguously resolve to this catalog; inspect the entry and use an absolute catalog script path before rerunning. Install with --skip-codex-hooks, or synchronize instructions without --codex-hook, to keep working with existing hooks.")
            found = True
    return found



def upgrade_legacy_session_hooks(groups: list, catalog: Path) -> list:
    """Explicitly adopt only plain catalog invocations, leaving custom commands intact."""
    retained = []
    script = (catalog / "hooks" / "direction_check_hook.py").resolve()
    declaration = json.loads(render_codex_hook_content({}, Path("hooks.json"), catalog, include_session_start=True))["hooks"]["SessionStart"][0]["hooks"][0]
    for group in groups:
        handlers = []
        for handler in group["hooks"]:
            if not existing_session_hook([{"hooks": [handler]}], catalog):
                handlers.append(handler)
                continue
            tokens = shlex.split(handler["command"])
            paths = [Path(os.path.expandvars(token)).expanduser() for token in tokens[2:]]
            script_count = sum(path.is_absolute() and path.resolve() == script for path in paths)
            allowed = {"--quiet", "--no-python-downloads", "--runtime-catchup"}
            plain = handler["command"] == declaration["command"] or (tokens[:2] == ["uv", "run"] and script_count == 1 and all(
                token in allowed or (path.is_absolute() and path.resolve() == script)
                for token, path in zip(tokens[2:], paths)
            ))
            if not plain:
                raise ValueError("Custom catalog session hook preserved: --upgrade-session-start only adopts plain uv run invocations. Omit this option to retain the custom hook while continuing setup.")
            # Keep matcher, handler position and native state keys stable. Only the
            # command and budget are adopted from the maintained declaration.
            upgraded = {**handler, "command": declaration["command"], "timeout": declaration["timeout"]}
            upgraded.pop("timeout_sec", None)
            handlers.append(upgraded)
        if handlers:
            retained.append({**group, "hooks": handlers})
    return retained


def prepare_codex_hooks(codex: Path, catalog: Path = ROOT, *, upgrade_session_start: bool = False) -> HookOutputs:
    """Move event definitions, leaving Codex-managed trust and settings in TOML."""
    hook_path, config_path = codex / "hooks.json", codex / "config.toml"
    hook_text = safe_content(hook_path)
    # A config symlink may remain a read-only source when it has no events to migrate.
    if config_path.exists() and not config_path.is_file():
        raise ValueError(f"Refusing a non-file configuration: {config_path}")
    config_text = config_path.read_bytes().decode() if config_path.exists() or config_path.is_symlink() else ""
    previous = {hook_path: hook_text.encode() if hook_path.exists() else None,
                config_path: config_text.encode() if config_path.exists() else None}
    config = json.loads(hook_text or "{}")
    settings = tomllib.loads(config_text)
    if not isinstance(config, dict) or not isinstance(config.get("hooks", {}), dict):
        raise ValueError("Invalid hooks.json configuration; inspect it before rerunning")
    hooks = config.setdefault("hooks", {})
    inline = settings.get("hooks", {})
    if not isinstance(inline, dict):
        raise ValueError("Invalid hooks configuration in config.toml")
    events = {event: groups for event, groups in inline.items() if event != "state"}
    states = inline.get("state", {})
    disabled_migrated = []
    if isinstance(states, dict):
        for event, groups in events.items():
            event_key = re.sub(r"(?<!^)(?=[A-Z])", "_", event).lower()
            for group_index, group in enumerate(groups if isinstance(groups, list) else []):
                handlers = group.get("hooks", []) if isinstance(group, dict) else []
                for handler_index, _ in enumerate(handlers if isinstance(handlers, list) else []):
                    suffix = f":{event_key}:{group_index}:{handler_index}"
                    for key, state in states.items():
                        if not (isinstance(key, str) and key.endswith(suffix) and isinstance(state, dict) and state.get("enabled") is False):
                            continue
                        if Path(key[:-len(suffix)]).resolve() == config_path.resolve():
                            disabled_migrated.append({"event": event, "source_group": group_index, "source_handler": handler_index})
                            break
    for event, groups in list(hooks.items()) + list(events.items()):
        if not isinstance(groups, list) or any(not isinstance(group, dict) or not isinstance(group.get("hooks"), list)
                                              or any(not isinstance(handler, dict) for handler in group["hooks"]) for group in groups):
            raise ValueError(f"Invalid {event} hook definition; inspect hooks.json and config.toml before rerunning. Install with --skip-codex-hooks, or synchronize instructions without --codex-hook, to keep working.")
    original_json_hooks = {event: list(groups) for event, groups in hooks.items()}
    for event, groups in events.items():
        existing = hooks.get(event, [])
        for group in groups:
            for other in existing:
                commands = {handler.get("command") for handler in group["hooks"] if isinstance(handler.get("command"), str)}
                other_commands = {handler.get("command") for handler in other["hooks"] if isinstance(handler.get("command"), str)}
                if group != other and group.get("matcher") == other.get("matcher") and commands & other_commands:
                    raise ValueError(f"Conflicting {event} definitions in both sources; reconcile the duplicate hooks before rerunning. Install with --skip-codex-hooks, or synchronize instructions without --codex-hook, to keep working.")
        hooks[event] = existing + [group for group in groups if group not in existing]
    sessions = hooks.get("SessionStart", [])
    if upgrade_session_start:
        # Native trust/state remains Codex-owned; this never fabricates approval.
        if any(item["event"] == "SessionStart" for item in disabled_migrated):
            raise ValueError("Disabled session hook preserved: omit --upgrade-session-start and review its disabled state in /hooks before upgrading.")
        sessions = hooks["SessionStart"] = upgrade_legacy_session_hooks(sessions, catalog)
    existing_session = existing_session_hook(sessions, catalog)
    try:
        json.dumps(config)
    except TypeError as exc:
        raise ValueError("Inline hooks contain values unsupported by hooks.json; inspect config.toml before rerunning") from exc
    outputs = {hook_path: render_codex_hook(hook_path, catalog, include_session_start=not existing_session, config=config)}
    rendered_hooks = json.loads(outputs[hook_path])["hooks"]
    for disabled in disabled_migrated:
        event = disabled["event"]
        original_group = events[event][disabled["source_group"]]
        destination_groups = rendered_hooks.get(event, [])
        if original_group in original_json_hooks.get(event, []):
            # The TOML duplicate was removed; its disabled choice must not be
            # attributed to the independently configured JSON copy.
            destination = None
            disabled["deduplicated"] = True
        else:
            occurrence = sum(group == original_group for group in events[event][:disabled["source_group"]])
            matches = [index for index, group in enumerate(destination_groups) if group == original_group]
            destination = matches[occurrence] if occurrence < len(matches) else None
        disabled["destination_group"] = destination
        disabled["destination_handler"] = disabled["source_handler"] if destination is not None else None
    if events:
        import tomlkit
        from tomlkit.items import AoT, Comment, Table

        if config_path.is_symlink():
            raise ValueError("Inline hooks in a symlinked config.toml are preserved. Install with --skip-codex-hooks, or synchronize instructions without --codex-hook, to keep working without touching hooks. Preserve the target contents in a regular config.toml before previewing migration again.")
        safe_content(config_path)
        document = tomlkit.parse(config_text)
        def comments(item):
            if isinstance(item, AoT):
                return [comment for table in item for comment in comments(table)]
            if isinstance(item, Table):
                return [comment for _, value in item.value.body for comment in comments(value)]
            return [item.as_string()] if isinstance(item, Comment) else []
        retained_comments = [comment for event in events for comment in comments(document["hooks"][event])]
        for event in events:
            del document["hooks"][event]
        if not document["hooks"]:
            del document["hooks"]
        cleaned = tomlkit.dumps(document)
        # TOML attaches comments above the next table to the preceding table.
        # Retain such comments, and comments on migrated declarations, as trivia.
        for comment in retained_comments:
            cleaned += ("" if cleaned.endswith("\n") else "\n") + comment
        expected = {**settings}
        remaining = {key: value for key, value in inline.items() if key not in events}
        if remaining:
            expected["hooks"] = remaining
        else:
            del expected["hooks"]
        if tomllib.loads(cleaned) != expected:
            raise ValueError("TOML migration would change unrelated settings; preserve the configuration and inspect it. Install with --skip-codex-hooks, or synchronize instructions without --codex-hook, to keep working.")
        outputs[config_path] = cleaned
    return HookOutputs(outputs, previous, {event: len(groups) for event, groups in events.items()}, disabled_migrated)


def write_codex_hooks(outputs: HookOutputs, codex: Path, catalog: Path = ROOT) -> list[dict[str, str]]:
    if prepare_codex_hooks(codex, catalog).previous != outputs.previous:
        raise ValueError("Hook configuration changed during preparation; preview again before writing")
    receipt = []
    try:
        for path, content in outputs.items():
            receipt.extend(synchronize(content, [path], write=True, expected_previous=outputs.previous))
    except (OSError, ValueError) as exc:
        backups = [entry["backup"] for entry in receipt if "backup" in entry]
        raise ValueError(f"Hook migration stopped: {exc}. Completed file backups: {backups}. Preview again; identical definitions reconcile on rerun.") from exc
    return receipt


def synchronize(content: str, destinations: list[Path], *, write: bool, local_source_missing: bool = False, allow_missing_local: bool = False, expected_previous: dict[Path, bytes | None] | None = None) -> list[dict[str, str]]:
    desired = content.encode()
    # Inspect every destination before writing either one.
    previous: dict[Path, bytes | None] = {}
    for path in destinations:
        if path.is_symlink() or (path.exists() and not path.is_file()):
            raise ValueError(f"Refusing a symlink or non-file destination: {path}")
        old = path.read_bytes() if path.exists() else None
        if expected_previous is not None and path in expected_previous and old != expected_previous[path]:
            raise ValueError(f"Destination changed since hook preview: {path}")
        previous[path] = old
        if old is not None and old != desired and local_source_missing and not allow_missing_local:
            msg = f"Local source is missing and {path.name} would change. {MISSING_LOCAL_RECOVERY}"
            if write:
                raise ValueError(f"Refusing to write {path}: {msg}")

    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    results = []
    for path, old in previous.items():
        entry = {"path": str(path), "sha256": hashlib.sha256(desired).hexdigest(), "state": "current"}
        if old != desired:
            if local_source_missing and not allow_missing_local and old is not None:
                msg = f"Local source is missing and {path.name} would change. {MISSING_LOCAL_RECOVERY}"
                entry["refusal"] = msg
                entry["state"] = "refused"
            else:
                entry["state"] = "written" if write else "would_write"
                
            if entry["state"] in ("would_write", "refused"):
                entry["diff"] = "".join(difflib.unified_diff(
                    (old or b"").decode().splitlines(keepends=True), content.splitlines(keepends=True),
                    fromfile=str(path), tofile=f"{path} (generated)",
                ))
            elif entry["state"] == "written":
                path.parent.mkdir(parents=True, exist_ok=True)
                if path.is_symlink() or (path.read_bytes() if path.exists() else None) != old:
                    raise ValueError(f"Destination changed during preparation: {path}")
                if old is not None:
                    backup = path.with_name(f"{path.name}.backup-{stamp}")
                    with backup.open("xb") as handle:
                        os.chmod(backup, 0o600)
                        handle.write(old)
                    entry["backup"] = str(backup)
                with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
                    staged = Path(handle.name)
                    handle.write(desired)
                try:
                    staged.replace(path)
                finally:
                    staged.unlink(missing_ok=True)
        results.append(entry)
    return results


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=ROOT / "instructions" / "global.md")
    parser.add_argument("--local-source", type=Path, default=ROOT / ".local" / "global-instructions.md")
    parser.add_argument("--home-dir", type=Path, help="Fixture home; overrides both native host destinations")
    parser.add_argument("--codex-dir", type=Path, help="Codex configuration directory (default CODEX_HOME, then ~/.codex)")
    parser.add_argument("--claude-dir", type=Path, help="Claude configuration directory (default CLAUDE_CONFIG_DIR, then ~/.claude)")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--allow-missing-local", action="store_true", help="Explicitly overwrite existing instruction files without the local source, dropping private instructions")
    parser.add_argument("--codex-hook", action="store_true", help="Consolidate Codex user hooks into hooks.json and register catalog hooks; trust remains Codex-managed")
    parser.add_argument("--hooks-only", action="store_true", help="Migrate/register Codex hooks without synchronizing global instructions")
    parser.add_argument("--upgrade-session-start", action="store_true", help="Explicitly replace plain legacy catalog startup invocations with the maintained declaration; native trust remains unchanged")
    parser.add_argument("--show-diff", action="store_true", help="Include full local diffs, which may contain private configuration")
    args = parser.parse_args()
    if args.home_dir and (args.codex_dir or args.claude_dir):
        parser.error("--home-dir cannot be combined with a host directory override")
    if args.home_dir:
        codex_dir, claude_dir = args.home_dir / ".codex", args.home_dir / ".claude"
    else:
        codex_dir = args.codex_dir or Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex")
        claude_dir = args.claude_dir or Path(os.environ.get("CLAUDE_CONFIG_DIR") or Path.home() / ".claude")
    try:
        if args.hooks_only and not args.codex_hook:
            parser.error("--hooks-only requires --codex-hook")
        if args.upgrade_session_start and not args.codex_hook:
            parser.error("--upgrade-session-start requires --codex-hook")
        hook_outputs = prepare_codex_hooks(codex_dir, upgrade_session_start=args.upgrade_session_start) if args.codex_hook else {}
        hook_previews = [entry for path, content in hook_outputs.items() for entry in synchronize(content, [path], write=False)]
        local_missing = not args.local_source.exists()
        outputs = [] if args.hooks_only else synchronize(render(args.source, args.local_source), [
            claude_dir / "CLAUDE.md", codex_dir / "AGENTS.md",
        ], write=args.write, local_source_missing=local_missing, allow_missing_local=args.allow_missing_local)
        if args.write:
            if hook_outputs:
                outputs.extend(write_codex_hooks(hook_outputs, codex_dir))
        else:
            outputs.extend(hook_previews)
    except (OSError, ValueError) as error:
        print(f"Synchronization stopped; earlier successful writes may remain: {error}", file=sys.stderr)
        return 1
    if not args.show_diff:
        for output in outputs:
            if Path(output["path"]) in hook_outputs:
                output.pop("diff", None)
    result: dict[str, object] = {"outputs": outputs}
    if args.codex_hook:
        result.update({"migrated_events": hook_outputs.migrated_events, "disabled_migrated_handlers": hook_outputs.disabled_migrated_handlers, "hook_trust": HOOK_TRUST_NOTICE})
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
