#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Render both hosts' global instructions from one catalog source bundle.

Preview by default. --write preserves each changed destination in a sibling
backup before replacing it. Private host instructions stay in the ignored
source .local/global-instructions.md, shared by both outputs.
"""

from __future__ import annotations

import argparse
import datetime as dt
import difflib
import hashlib
import json
import os
import shlex
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = "<!-- Generated by codex-skills/scripts/sync-global-instructions.py; edit the catalog source. -->"
HOOK_LABEL = "codex-skills command policies"


def render(source: Path, local_source: Path) -> str:
    sections = [HEADER, source.read_text().strip()]
    if local_source.exists():
        sections.append(local_source.read_text().strip())
    return "\n\n".join(section for section in sections if section) + "\n"


def render_codex_hook(destination: Path, catalog: Path = ROOT) -> str:
    """Bind the same PreToolUse declaration without changing other host hooks."""
    if destination.is_symlink() or (destination.exists() and not destination.is_file()):
        raise ValueError(f"Refusing a symlink or non-file destination: {destination}")
    config = json.loads(destination.read_text()) if destination.exists() else {}
    if not isinstance(config, dict) or not isinstance(config.get("hooks", {}), dict):
        raise ValueError(f"Invalid hooks configuration: {destination}")
    hooks = config.setdefault("hooks", {})
    existing = hooks.get("PreToolUse", [])
    if not isinstance(existing, list):
        raise ValueError(f"Invalid PreToolUse configuration: {destination}")
    declarations = json.loads((catalog / "hooks" / "hooks.json").read_text())["hooks"]["PreToolUse"]
    for group in declarations:
        for handler in group["hooks"]:
            handler["command"] = shlex.join([
                "env", f"CLAUDE_PLUGIN_ROOT={catalog}", "sh", "-c", handler["command"],
            ])
            handler["statusMessage"] = HOOK_LABEL
    hooks["PreToolUse"] = [group for group in existing if not (
        isinstance(group, dict) and len(group.get("hooks", [])) == 1
        and isinstance(group["hooks"][0], dict) and group["hooks"][0].get("statusMessage") == HOOK_LABEL
    )] + declarations
    return json.dumps(config, indent=2) + "\n"


def synchronize(content: str, destinations: list[Path], *, write: bool) -> list[dict[str, str]]:
    # Inspect every destination before writing either one.
    previous: dict[Path, bytes | None] = {}
    for path in destinations:
        if path.is_symlink() or (path.exists() and not path.is_file()):
            raise ValueError(f"Refusing a symlink or non-file destination: {path}")
        previous[path] = path.read_bytes() if path.exists() else None
    desired = content.encode()
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    results = []
    for path, old in previous.items():
        entry = {"path": str(path), "sha256": hashlib.sha256(desired).hexdigest(), "state": "current"}
        if old != desired:
            entry["state"] = "written" if write else "would_write"
            if not write:
                entry["diff"] = "".join(difflib.unified_diff(
                    (old or b"").decode().splitlines(keepends=True), content.splitlines(keepends=True),
                    fromfile=str(path), tofile=f"{path} (generated)",
                ))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                if path.is_symlink() or (path.read_bytes() if path.exists() else None) != old:
                    raise ValueError(f"Destination changed during preparation: {path}")
                if old is not None:
                    backup = path.with_name(f"{path.name}.backup-{stamp}")
                    with backup.open("xb") as handle:
                        os.chmod(backup, 0o600)
                        handle.write(old)
                    entry["backup"] = str(backup)
                with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
                    staged = Path(handle.name)
                    handle.write(desired)
                try:
                    staged.replace(path)
                finally:
                    staged.unlink(missing_ok=True)
        results.append(entry)
    return results


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=ROOT / "instructions" / "global.md")
    parser.add_argument("--local-source", type=Path, default=ROOT / ".local" / "global-instructions.md")
    parser.add_argument("--home-dir", type=Path, help="Fixture home; overrides both native host destinations")
    parser.add_argument("--codex-dir", type=Path, help="Codex configuration directory (default CODEX_HOME, then ~/.codex)")
    parser.add_argument("--claude-dir", type=Path, help="Claude configuration directory (default CLAUDE_CONFIG_DIR, then ~/.claude)")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--codex-hook", action="store_true", help="Also register the catalog's PreToolUse hook in .codex/hooks.json; host hook trust is unchanged")
    args = parser.parse_args()
    if args.home_dir and (args.codex_dir or args.claude_dir):
        parser.error("--home-dir cannot be combined with a host directory override")
    if args.home_dir:
        codex_dir, claude_dir = args.home_dir / ".codex", args.home_dir / ".claude"
    else:
        codex_dir = args.codex_dir or Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex")
        claude_dir = args.claude_dir or Path(os.environ.get("CLAUDE_CONFIG_DIR") or Path.home() / ".claude")
    try:
        hook_destination = codex_dir / "hooks.json"
        hook_content = render_codex_hook(hook_destination) if args.codex_hook else None
        outputs = synchronize(render(args.source, args.local_source), [
            claude_dir / "CLAUDE.md", codex_dir / "AGENTS.md",
        ], write=args.write)
        if hook_content is not None:
            outputs.extend(synchronize(hook_content, [hook_destination], write=args.write))
    except (OSError, ValueError) as error:
        print(f"Global instructions not synchronized: {error}", file=sys.stderr)
        return 1
    print(json.dumps({"outputs": outputs}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
