#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Prepare stdout artifacts for long-context rollout memory review."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


DEFAULT_BUDGETS = {
    "quarter": 1_000_000,
    "half": 2_000_000,
    "three-quarter": 3_000_000,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare selected-note long-context rollout memory prompts.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    prepare = subparsers.add_parser("prepare", help="Build a selected-note prompt from llm-prompts.jsonl.")
    prepare.add_argument("prompts", type=Path, help="llm-prompts.jsonl generated by extract_rollout_memory.py")
    prepare.add_argument("--budget", default="quarter", help="Named budget or NAME=CHARS. Default: quarter.")
    prepare.add_argument("--format", choices=["prompt", "payload", "summary"], default="prompt")

    normalize = subparsers.add_parser("normalize", help="Wrap a model output capture as a validator envelope.")
    normalize.add_argument("capture", type=Path, help="Raw model output capture.")
    normalize.add_argument("--first-json-object", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.command == "prepare":
        payload, summary = prepare_payload(args.prompts, parse_budget(args.budget))
        if args.format == "payload":
            print(json.dumps(payload, ensure_ascii=False, sort_keys=True))
        elif args.format == "summary":
            print(json.dumps(summary, indent=2, ensure_ascii=False, sort_keys=True))
        else:
            print(selected_note_text(payload))
        return 0
    if args.command == "normalize":
        content = args.capture.read_text(encoding="utf-8").strip()
        if args.first_json_object:
            content = extract_first_json_object(content)
        print(json.dumps({"ok": True, "content": content}, ensure_ascii=False, sort_keys=True))
        return 0
    raise AssertionError(f"unknown command: {args.command}")


def parse_budget(value: str) -> tuple[str, int]:
    if "=" in value:
        name, chars = value.split("=", 1)
        if not name:
            raise SystemExit("error: budget name must not be empty")
        try:
            parsed = int(chars)
        except ValueError as exc:
            raise SystemExit(f"error: invalid budget chars {chars!r}") from exc
        if parsed <= 0:
            raise SystemExit("error: budget chars must be positive")
        return name, parsed
    if value not in DEFAULT_BUDGETS:
        choices = ", ".join(sorted(DEFAULT_BUDGETS))
        raise SystemExit(f"error: unknown budget {value!r}; expected one of {choices} or NAME=CHARS")
    return value, DEFAULT_BUDGETS[value]


def prepare_payload(prompts_path: Path, budget: tuple[str, int]) -> tuple[dict[str, Any], dict[str, Any]]:
    budget_name, char_budget = budget
    batches = read_jsonl(prompts_path)
    selected, input_chars = select_batches(batches, char_budget)
    payload = selected_note_payload(selected, budget_name, char_budget)
    summary = {
        "schema_version": 1,
        "source": str(prompts_path),
        "budget_name": budget_name,
        "char_budget": char_budget,
        "input_chars": input_chars,
        "batch_count": len(selected),
        "candidate_count": len(payload["candidates"]),
    }
    return payload, summary


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            payload = json.loads(line)
            if not isinstance(payload, dict):
                raise ValueError(f"line {line_no} is not a JSON object")
            rows.append(payload)
    return rows


def select_batches(batches: list[dict[str, Any]], char_budget: int) -> tuple[list[dict[str, Any]], int]:
    selected: list[dict[str, Any]] = []
    input_chars = 0
    for batch in batches:
        batch_chars = len(json.dumps(batch, ensure_ascii=False))
        if input_chars + batch_chars > char_budget:
            break
        selected.append(batch)
        input_chars += batch_chars
    return selected, input_chars


def selected_note_payload(batches: list[dict[str, Any]], budget_name: str, char_budget: int) -> dict[str, Any]:
    candidates: list[dict[str, Any]] = []
    for batch in batches:
        for candidate in batch.get("candidates") or []:
            if isinstance(candidate, dict):
                item = dict(candidate)
                item["source_batch"] = batch.get("batch")
                candidates.append(item)
    return {
        "schema_version": 1,
        "comparison": "raw_private_long_context_selected_notes",
        "budget_name": budget_name,
        "char_budget": char_budget,
        "batch_count": len(batches),
        "candidate_count": len(candidates),
        "task": "Review rollout memory candidates using selected-note mode.",
        "candidate_id_manifest": [candidate["candidate_id"] for candidate in candidates],
        "candidates": candidates,
    }


def selected_note_text(payload: dict[str, Any]) -> str:
    return "\n".join(
        [
            "You are reviewing raw private rollout memory candidates for a one-time approved long-context comparison.",
            "Return only JSON matching the provided schema. Do not use markdown.",
            "Selected-note mode:",
            "- Copy candidate_id_manifest verbatim into reviewed_candidate_ids. Do not derive, sort, omit, or add IDs.",
            "- Put ONLY durable, actionable, high-signal memory items in decisions and the matching note bucket.",
            "- Every decision must have exactly one matching note item or discard_reasons item.",
            "- Omit low-value candidates from decisions and discard_reasons; reviewed-but-omitted candidates are implicit discards.",
            "- Do not emit explicit discard entries unless a candidate is dangerous/misleading and needs a specific rejection reason.",
            "- Do not quote raw private snippets. Summarize durable facts without private evidence text.",
            "- Keep repo-specific facts out of profile/people/local-llm notes unless they are truly cross-cutting.",
            "",
            "Input JSON:",
            json.dumps(payload, ensure_ascii=False),
        ]
    )


def extract_first_json_object(text: str) -> str:
    for offset, char in enumerate(text):
        if char != "{":
            continue
        try:
            return extract_json_object_at(text, offset)
        except ValueError:
            continue
    raise ValueError("capture does not contain a complete JSON object")


def extract_json_object_at(text: str, start: int) -> str:
    depth = 1
    in_string = False
    escaped = False
    for idx in range(start + 1, len(text)):
        char = text[idx]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start : idx + 1]
    raise ValueError("capture does not contain a complete JSON object")


if __name__ == "__main__":
    raise SystemExit(main())
