#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Run stdout-only long-context rollout memory model matrix checks."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

from prepare_rollout_memory_long_context_review import (
    PromptTooLargeError,
    extract_first_json_object,
    parse_budget,
    prepare_payload,
    selected_note_text,
)
from validate_rollout_memory_llm_results import ValidationError, validate_content


DEFAULT_VARIANTS = [
    "gpt-5.4=code-llm:gpt-5.4",
    "sonnet-1m=claude:claude-sonnet-4-6[1m]",
    "opus=claude:opus",
]
DEFAULT_SYSTEM = (
    "You are a strict selected-note memory reviewer. Return only JSON that matches the schema. "
    "Do not quote raw private snippets. Copy candidate_id_manifest verbatim into reviewed_candidate_ids."
)
DEFAULT_SKIP_STATUSES = {"passed"}
SUCCESS_STATUSES = {"passed", "planned", "skipped_existing"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run rollout memory long-context model matrix checks.")
    parser.add_argument("prompts", type=Path, help="llm-prompts.jsonl generated by extract_rollout_memory.py")
    parser.add_argument("--budget", action="append", default=[], help="Budget name or NAME=CHARS. May be repeated.")
    parser.add_argument("--variant", action="append", default=[], help="NAME=PROVIDER:MODEL. Providers: code-llm, claude.")
    parser.add_argument("--schema-file", type=Path, help="Strict JSON schema file for provider structured output.")
    parser.add_argument("--output-jsonl", type=Path, help="Append matrix rows to this JSONL file.")
    parser.add_argument("--output-dir", type=Path, help="Write per-row normalized cloud output artifacts.")
    parser.add_argument("--skip-existing", action="store_true", help="Skip rows already present in --output-jsonl.")
    parser.add_argument(
        "--skip-status",
        action="append",
        default=[],
        help="When --skip-existing is set, skip existing rows with this status. Defaults to passed.",
    )
    parser.add_argument(
        "--retry-status",
        action="append",
        default=[],
        help="Existing status to retry even if it is included by --skip-status. May be repeated.",
    )
    parser.add_argument("--max-seconds", type=float, default=1800.0)
    parser.add_argument("--anthropic-max-budget-usd", type=float, default=3.0)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--allow-private-cloud", action="store_true")
    parser.add_argument(
        "--confirm-private-provider",
        action="append",
        default=[],
        choices=["code-llm", "claude"],
        help="Confirm a provider that may receive private prompt content in this run. Required with --allow-private-cloud.",
    )
    args = parser.parse_args()
    variants = [parse_variant(value) for value in (args.variant or DEFAULT_VARIANTS)]
    args.parsed_variants = variants
    return args


def main() -> int:
    args = parse_args()
    budgets = [parse_budget(value) for value in (args.budget or ["quarter"])]
    variants = args.parsed_variants
    existing = read_existing_rows(args.output_jsonl) if args.skip_existing and args.output_jsonl else {}
    skip_statuses = parse_status_filter(args.skip_status, DEFAULT_SKIP_STATUSES) - parse_status_filter(
        args.retry_status, set()
    )
    rows: list[dict[str, Any]] = []
    for budget in budgets:
        prompt_error: PromptTooLargeError | None = None
        try:
            payload, prompt_summary = prepare_payload(args.prompts, budget)
            prompt = selected_note_text(payload)
            prompt_summary["prompt_sha256"] = sha256_text(prompt)
        except PromptTooLargeError as exc:
            payload = None
            prompt = None
            prompt_summary = prompt_too_large_summary(args.prompts, budget, exc)
            prompt_error = exc
        for variant in variants:
            key = row_key(prompt_summary["budget_name"], variant)
            existing_rows = existing.get(key, [])
            reusable_row = reusable_existing_row(existing_rows, skip_statuses, prompt_summary)
            if reusable_row is not None:
                row = {**reusable_row, "status": "skipped_existing", "original_status": reusable_row.get("status")}
            elif prompt_error is not None:
                row = prompt_too_large_row(prompt_summary, variant, prompt_error)
            else:
                if payload is None or prompt is None:
                    raise AssertionError("prompt payload should exist when no prompt error was recorded")
                row = run_or_plan(payload, prompt, prompt_summary, variant, args)
            if row.get("status") != "skipped_existing" and args.output_jsonl:
                append_jsonl(args.output_jsonl, row)
            rows.append(row)
            print(json.dumps(row, ensure_ascii=False, sort_keys=True), flush=True)
    summary = summarize_rows(rows)
    print(json.dumps(summary, ensure_ascii=False, sort_keys=True), flush=True)
    return 0 if all(row["status"] in SUCCESS_STATUSES for row in rows) else 1


def parse_status_filter(values: list[str], default: set[str]) -> set[str]:
    if not values:
        return set(default)
    statuses: set[str] = set()
    for value in values:
        statuses.update(status.strip() for status in value.split(",") if status.strip())
    return statuses


def parse_variant(value: str) -> dict[str, str]:
    name, sep, rest = value.partition("=")
    provider, sep2, model = rest.partition(":")
    if not sep or not sep2 or provider not in {"code-llm", "claude"} or not name.strip() or not model:
        raise SystemExit(f"error: invalid variant {value!r}; expected NAME=PROVIDER:MODEL")
    return {"name": name.strip(), "provider": provider, "model": model}


def validate_private_provider_approval(
    args: argparse.Namespace, variants: list[dict[str, str]], parser: argparse.ArgumentParser
) -> None:
    if args.dry_run:
        return
    providers = sorted({variant["provider"] for variant in variants})
    if not args.allow_private_cloud:
        parser.error("--allow-private-cloud is required for non-dry-run provider calls")
    confirmed = set(args.confirm_private_provider or [])
    missing = [provider for provider in providers if provider not in confirmed]
    if missing:
        parser.error(
            "--confirm-private-provider must include each non-dry-run provider: " + ", ".join(missing)
        )


def run_or_plan(
    payload: dict[str, Any], prompt: str, prompt_summary: dict[str, Any], variant: dict[str, str], args: argparse.Namespace
) -> dict[str, Any]:
    row: dict[str, Any] = {
        "schema_version": 1,
        "budget_name": prompt_summary["budget_name"],
        "variant": variant,
        "candidate_count": prompt_summary["candidate_count"],
        "input_chars": prompt_summary["input_chars"],
        "prompt_chars": len(prompt),
        "prompt_sha256": prompt_summary["prompt_sha256"],
    }
    if args.dry_run:
        row["status"] = "planned"
        return row
    started = time.time()
    try:
        require_private_provider_approval(args, variant)
        if variant["provider"] == "code-llm":
            content = request_code_llm(variant["model"], prompt, args)
        else:
            content = request_claude(variant["model"], prompt, args)
        validation = validate_content(payload, content, allow_implicit_discards=True)
        row.update(validation)
        row["status"] = "passed" if validation.get("ok") else "failed_validation"
        if args.output_dir:
            row["artifacts"] = persist_matrix_output(args.output_dir, prompt_summary, variant, content, validation)
    except MatrixBlocked as exc:
        row["status"] = exc.status
        row["error"] = str(exc)
    except subprocess.TimeoutExpired as exc:
        row["status"] = "timeout"
        row["error"] = f"timed out after {exc.timeout:g}s"
    except subprocess.CalledProcessError as exc:
        message = command_error_message(exc)
        row["status"] = classify_error(message)
        row["error"] = message
    except (OSError, ValueError, json.JSONDecodeError, ValidationError) as exc:
        row["status"] = classify_error(str(exc))
        row["error"] = str(exc)
    row["elapsed_seconds"] = round(time.time() - started, 3)
    return row


def require_private_provider_approval(args: argparse.Namespace, variant: dict[str, str]) -> None:
    if not args.allow_private_cloud:
        raise MatrixBlocked("blocked_approval", "--allow-private-cloud is required before provider calls")
    confirmed = set(args.confirm_private_provider or [])
    provider = variant["provider"]
    if provider not in confirmed:
        raise MatrixBlocked(
            "blocked_approval",
            f"--confirm-private-provider must include provider before provider calls: {provider}",
        )


class MatrixBlocked(RuntimeError):
    def __init__(self, status: str, message: str) -> None:
        super().__init__(message)
        self.status = status


def prompt_too_large_summary(prompts_path: Path, budget: tuple[str, int], exc: PromptTooLargeError) -> dict[str, Any]:
    budget_name, char_budget = budget
    return {
        "schema_version": 1,
        "source": str(prompts_path),
        "budget_name": budget_name,
        "char_budget": char_budget,
        "input_chars": 0,
        "batch_count": 0,
        "candidate_count": 0,
        "error": str(exc),
    }


def prompt_too_large_row(prompt_summary: dict[str, Any], variant: dict[str, str], exc: PromptTooLargeError) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "budget_name": prompt_summary["budget_name"],
        "variant": variant,
        "candidate_count": prompt_summary["candidate_count"],
        "input_chars": prompt_summary["input_chars"],
        "prompt_chars": 0,
        "prompt_sha256": prompt_summary.get("prompt_sha256"),
        "status": "prompt_too_large",
        "error": str(exc),
        "elapsed_seconds": 0.0,
    }


def persist_matrix_output(
    output_dir: Path, prompt_summary: dict[str, Any], variant: dict[str, str], content: str, validation: dict[str, Any]
) -> dict[str, str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = safe_artifact_stem(prompt_summary["budget_name"], variant)
    content_path = output_dir / f"{stem}.content.json"
    validation_path = output_dir / f"{stem}.validation.json"
    content_path.write_text(content, encoding="utf-8")
    validation_path.write_text(json.dumps(validation, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
    return {"content": str(content_path), "validation": str(validation_path)}


def safe_artifact_stem(budget_name: str, variant: dict[str, str]) -> str:
    raw = "-".join([budget_name, variant["name"], variant["provider"], variant["model"]])
    cleaned = "".join(char if char.isalnum() or char in {"-", "_", "."} else "_" for char in raw)
    return cleaned.strip("._-") or "matrix-row"


def request_code_llm(model: str, prompt: str, args: argparse.Namespace) -> str:
    argv_limit = os.sysconf("SC_ARG_MAX") if hasattr(os, "sysconf") else 1_000_000
    schema_chars = len(compact_json(default_schema())) if not args.schema_file else len(str(args.schema_file))
    estimated_argv_chars = len(DEFAULT_SYSTEM) + schema_chars + len(model) + 4_000
    if estimated_argv_chars > int(argv_limit * 0.9):
        raise MatrixBlocked(
            "blocked_transport",
            f"estimated argv is {estimated_argv_chars} chars; code llm request schema args exceed this host ARG_MAX of {argv_limit}",
        )
    schema_args = ["--schema-file", str(args.schema_file)] if args.schema_file else ["--schema-json", compact_json(default_schema())]
    with tempfile.TemporaryDirectory(prefix="rollout-memory-code-llm-") as tmp:
        prompt_path = Path(tmp) / "prompt.txt"
        prompt_path.write_text(prompt, encoding="utf-8")
        command = code_llm_command(model, prompt_path, schema_args)
        result = subprocess.run(command, capture_output=True, text=True, timeout=args.max_seconds, check=True)
    return extract_first_json_object(result.stdout.strip())


def code_llm_command(model: str, prompt_path: Path, schema_args: list[str]) -> list[str]:
    return [
        "code",
        "llm",
        "request",
        "--developer",
        DEFAULT_SYSTEM,
        "--message-file",
        str(prompt_path),
        *schema_args,
        "--format-name",
        "RolloutMemoryReview",
        "--format-strict",
        "--model",
        model,
    ]


def request_claude(model: str, prompt: str, args: argparse.Namespace) -> str:
    schema = compact_json(read_json(args.schema_file)) if args.schema_file else compact_json(default_schema())
    command = [
        "claude",
        "-p",
        "--model",
        model,
        "--output-format",
        "json",
        "--json-schema",
        schema,
        "--max-budget-usd",
        f"{args.anthropic_max_budget_usd:g}",
    ]
    result = subprocess.run(command, input=prompt, capture_output=True, text=True, timeout=args.max_seconds, check=True)
    raw = json.loads(result.stdout)
    if not isinstance(raw, dict):
        raise ValueError("Claude CLI output was not a JSON object")
    content = raw.get("result")
    if raw.get("is_error"):
        raise MatrixBlocked(classify_error(str(content or raw)), str(content or raw))
    if not isinstance(content, str):
        raise ValueError("Claude CLI output did not contain a string result")
    return extract_first_json_object(content.strip())


def classify_error(message: str) -> str:
    folded = message.casefold()
    if "usage credits required" in folded or "may not exist or you may not have access" in folded:
        return "blocked_access"
    if "maximum budget" in folded or "max_budget_usd" in folded:
        return "budget_exceeded"
    if "argv" in folded or "arg_max" in folded:
        return "blocked_transport"
    if "prompt_too_large" in folded or "no prompt batch fits" in folded:
        return "prompt_too_large"
    if "not strict json" in folded or "does not start with a json object" in folded:
        return "failed_json"
    return "error"


def command_error_message(exc: subprocess.CalledProcessError) -> str:
    parts = []
    if exc.stdout:
        parts.append(str(exc.stdout).strip())
    if exc.stderr:
        parts.append(str(exc.stderr).strip())
    if parts:
        return "\n".join(part for part in parts if part)
    return str(exc)


def summarize_rows(rows: list[dict[str, Any]]) -> dict[str, Any]:
    counts: dict[str, int] = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1
    return {"schema_version": 1, "summary": True, "run_count": len(rows), "status_counts": counts}


def row_key(budget_name: str, variant: dict[str, str]) -> tuple[str, str, str, str]:
    return (budget_name, variant["name"], variant["provider"], variant["model"])


def reusable_existing_row(
    rows: list[dict[str, Any]], skip_statuses: set[str], prompt_summary: dict[str, Any]
) -> dict[str, Any] | None:
    for row in reversed(rows):
        if row.get("status") not in skip_statuses:
            continue
        if row.get("prompt_sha256") == prompt_summary.get("prompt_sha256"):
            return row
    return None


def read_existing_rows(path: Path) -> dict[tuple[str, str, str, str], list[dict[str, Any]]]:
    rows: dict[tuple[str, str, str, str], list[dict[str, Any]]] = {}
    if not path.exists():
        return rows
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            payload = json.loads(line)
            if isinstance(payload, dict) and not payload.get("summary") and isinstance(payload.get("variant"), dict):
                budget = payload.get("budget_name")
                name = payload["variant"].get("name")
                provider = payload["variant"].get("provider")
                model = payload["variant"].get("model")
                if (
                    isinstance(budget, str)
                    and isinstance(name, str)
                    and isinstance(provider, str)
                    and isinstance(model, str)
                ):
                    rows.setdefault((budget, name, provider, model), []).append(payload)
    return rows


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def append_jsonl(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(payload, ensure_ascii=False, sort_keys=True))
        handle.write("\n")


def default_schema() -> dict[str, Any]:
    note_item = {
        "type": "object",
        "additionalProperties": False,
        "required": ["candidate_id", "note", "reason"],
        "properties": {"candidate_id": {"type": "string"}, "note": {"type": "string"}, "reason": {"type": "string"}},
    }
    return {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "decisions",
            "people_updates",
            "profile_notes",
            "rollout_friction_notes",
            "local_llm_notes",
            "repo_specific_notes",
            "discard_reasons",
            "reviewed_candidate_ids",
        ],
        "properties": {
            "decisions": {"type": "array", "items": decision_item()},
            "people_updates": {"type": "array", "items": note_item},
            "profile_notes": {"type": "array", "items": note_item},
            "rollout_friction_notes": {"type": "array", "items": note_item},
            "local_llm_notes": {"type": "array", "items": note_item},
            "repo_specific_notes": {"type": "array", "items": note_item},
            "discard_reasons": {"type": "array", "items": discard_item()},
            "reviewed_candidate_ids": {"type": "array", "items": {"type": "string"}},
        },
    }


def decision_item() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["candidate_id", "action", "destination", "reason"],
        "properties": {
            "candidate_id": {"type": "string"},
            "action": {"type": "string", "enum": ["note", "discard"]},
            "destination": {
                "type": "string",
                "enum": [
                    "people_updates",
                    "profile_notes",
                    "rollout_friction_notes",
                    "local_llm_notes",
                    "repo_specific_notes",
                    "discard_reasons",
                ],
            },
            "reason": {"type": "string"},
        },
    }


def discard_item() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["candidate_id", "reason"],
        "properties": {"candidate_id": {"type": "string"}, "reason": {"type": "string"}},
    }


def read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"{path} did not contain a JSON object")
    return payload


def compact_json(payload: object) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


if __name__ == "__main__":
    raise SystemExit(main())
