#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Run stdout-only long-context rollout memory model matrix checks."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from prepare_rollout_memory_long_context_review import extract_first_json_object, parse_budget, prepare_payload, selected_note_text
from validate_rollout_memory_llm_results import ValidationError, validate_content


DEFAULT_VARIANTS = [
    "gpt-5.4=code-llm:gpt-5.4",
    "sonnet-1m=claude:claude-sonnet-4-6[1m]",
    "opus=claude:opus",
]
DEFAULT_SYSTEM = (
    "You are a strict selected-note memory reviewer. Return only JSON that matches the schema. "
    "Do not quote raw private snippets. Copy candidate_id_manifest verbatim into reviewed_candidate_ids."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run rollout memory long-context model matrix checks.")
    parser.add_argument("prompts", type=Path, help="llm-prompts.jsonl generated by extract_rollout_memory.py")
    parser.add_argument("--budget", action="append", default=[], help="Budget name or NAME=CHARS. May be repeated.")
    parser.add_argument("--variant", action="append", default=[], help="NAME=PROVIDER:MODEL. Providers: code-llm, claude.")
    parser.add_argument("--schema-file", type=Path, help="Strict JSON schema file for provider structured output.")
    parser.add_argument("--output-jsonl", type=Path, help="Append matrix rows to this JSONL file.")
    parser.add_argument("--skip-existing", action="store_true", help="Skip rows already present in --output-jsonl.")
    parser.add_argument(
        "--skip-status",
        action="append",
        default=[],
        help="When --skip-existing is set, skip existing rows with this status. Defaults to passed.",
    )
    parser.add_argument("--max-seconds", type=float, default=1800.0)
    parser.add_argument("--anthropic-max-budget-usd", type=float, default=3.0)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--allow-private-cloud", action="store_true")
    args = parser.parse_args()
    if not args.dry_run and not args.allow_private_cloud:
        parser.error("--allow-private-cloud is required for non-dry-run provider calls")
    return args


def main() -> int:
    args = parse_args()
    budgets = [parse_budget(value) for value in (args.budget or ["quarter"])]
    variants = [parse_variant(value) for value in (args.variant or DEFAULT_VARIANTS)]
    existing = read_existing_rows(args.output_jsonl) if args.skip_existing and args.output_jsonl else {}
    skip_statuses = set(args.skip_status or ["passed"])
    rows: list[dict[str, Any]] = []
    for budget in budgets:
        payload, prompt_summary = prepare_payload(args.prompts, budget)
        prompt = selected_note_text(payload)
        for variant in variants:
            key = row_key(prompt_summary["budget_name"], variant)
            existing_row = existing.get(key)
            if should_skip_existing(existing_row, skip_statuses):
                row = {**existing_row, "status": "skipped_existing", "original_status": existing_row.get("status")}
            else:
                row = run_or_plan(payload, prompt, prompt_summary, variant, args)
            if row.get("status") != "skipped_existing" and args.output_jsonl:
                append_jsonl(args.output_jsonl, row)
            rows.append(row)
            print(json.dumps(row, ensure_ascii=False, sort_keys=True), flush=True)
    summary = summarize_rows(rows)
    print(json.dumps(summary, ensure_ascii=False, sort_keys=True), flush=True)
    return 0 if all(row["status"] in {"passed", "planned", "skipped_existing"} for row in rows) else 1


def parse_variant(value: str) -> dict[str, str]:
    name, sep, rest = value.partition("=")
    provider, sep2, model = rest.partition(":")
    if not sep or not sep2 or provider not in {"code-llm", "claude"} or not name.strip() or not model:
        raise SystemExit(f"error: invalid variant {value!r}; expected NAME=PROVIDER:MODEL")
    return {"name": name.strip(), "provider": provider, "model": model}


def run_or_plan(
    payload: dict[str, Any], prompt: str, prompt_summary: dict[str, Any], variant: dict[str, str], args: argparse.Namespace
) -> dict[str, Any]:
    row: dict[str, Any] = {
        "schema_version": 1,
        "budget_name": prompt_summary["budget_name"],
        "variant": variant,
        "candidate_count": prompt_summary["candidate_count"],
        "input_chars": prompt_summary["input_chars"],
        "prompt_chars": len(prompt),
    }
    if args.dry_run:
        row["status"] = "planned"
        return row
    if not payload.get("candidates"):
        row["status"] = "prompt_too_large"
        row["error"] = "no prompt batch fits within the requested budget"
        row["elapsed_seconds"] = 0.0
        return row
    started = time.time()
    try:
        if variant["provider"] == "code-llm":
            content = request_code_llm(variant["model"], prompt, args)
        else:
            content = request_claude(variant["model"], prompt, args)
        validation = validate_content(payload, content, allow_implicit_discards=True)
        row.update(validation)
        row["status"] = "passed" if validation.get("ok") else "failed_validation"
    except MatrixBlocked as exc:
        row["status"] = exc.status
        row["error"] = str(exc)
    except subprocess.TimeoutExpired as exc:
        row["status"] = "timeout"
        row["error"] = f"timed out after {exc.timeout:g}s"
    except subprocess.CalledProcessError as exc:
        message = command_error_message(exc)
        row["status"] = classify_error(message)
        row["error"] = message
    except (OSError, ValueError, json.JSONDecodeError, ValidationError) as exc:
        row["status"] = classify_error(str(exc))
        row["error"] = str(exc)
    row["elapsed_seconds"] = round(time.time() - started, 3)
    return row


class MatrixBlocked(RuntimeError):
    def __init__(self, status: str, message: str) -> None:
        super().__init__(message)
        self.status = status


def request_code_llm(model: str, prompt: str, args: argparse.Namespace) -> str:
    argv_limit = os.sysconf("SC_ARG_MAX") if hasattr(os, "sysconf") else 1_000_000
    schema_chars = len(compact_json(default_schema())) if not args.schema_file else len(str(args.schema_file))
    estimated_argv_chars = len(prompt) + schema_chars + 4_000
    if estimated_argv_chars > int(argv_limit * 0.9):
        raise MatrixBlocked(
            "blocked_transport",
            f"estimated argv is {estimated_argv_chars} chars; code llm request requires argv and this host ARG_MAX is {argv_limit}",
        )
    schema_args = ["--schema-file", str(args.schema_file)] if args.schema_file else ["--schema-json", compact_json(default_schema())]
    command = [
        "code",
        "llm",
        "request",
        "--developer",
        DEFAULT_SYSTEM,
        "--message",
        prompt,
        *schema_args,
        "--format-name",
        "RolloutMemoryReview",
        "--format-strict",
        "--model",
        model,
    ]
    result = subprocess.run(command, capture_output=True, text=True, timeout=args.max_seconds, check=True)
    return extract_first_json_object(result.stdout.strip())


def request_claude(model: str, prompt: str, args: argparse.Namespace) -> str:
    schema = compact_json(read_json(args.schema_file)) if args.schema_file else compact_json(default_schema())
    command = [
        "claude",
        "-p",
        "--model",
        model,
        "--output-format",
        "json",
        "--json-schema",
        schema,
        "--max-budget-usd",
        f"{args.anthropic_max_budget_usd:g}",
    ]
    result = subprocess.run(command, input=prompt, capture_output=True, text=True, timeout=args.max_seconds, check=True)
    raw = json.loads(result.stdout)
    if not isinstance(raw, dict):
        raise ValueError("Claude CLI output was not a JSON object")
    content = raw.get("result")
    if raw.get("is_error"):
        raise MatrixBlocked(classify_error(str(content or raw)), str(content or raw))
    if not isinstance(content, str):
        raise ValueError("Claude CLI output did not contain a string result")
    return extract_first_json_object(content.strip())


def classify_error(message: str) -> str:
    folded = message.casefold()
    if "usage credits required" in folded or "may not exist or you may not have access" in folded:
        return "blocked_access"
    if "maximum budget" in folded or "max_budget_usd" in folded:
        return "budget_exceeded"
    if "argv" in folded or "arg_max" in folded:
        return "blocked_transport"
    if "prompt_too_large" in folded or "no prompt batch fits" in folded:
        return "prompt_too_large"
    if "not strict json" in folded or "does not start with a json object" in folded:
        return "failed_json"
    return "error"


def command_error_message(exc: subprocess.CalledProcessError) -> str:
    parts = []
    if exc.stdout:
        parts.append(str(exc.stdout).strip())
    if exc.stderr:
        parts.append(str(exc.stderr).strip())
    if parts:
        return "\n".join(part for part in parts if part)
    return str(exc)


def summarize_rows(rows: list[dict[str, Any]]) -> dict[str, Any]:
    counts: dict[str, int] = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1
    return {"schema_version": 1, "summary": True, "run_count": len(rows), "status_counts": counts}


def row_key(budget_name: str, variant: dict[str, str]) -> tuple[str, str]:
    return (budget_name, variant["name"])


def should_skip_existing(row: dict[str, Any] | None, skip_statuses: set[str]) -> bool:
    return bool(row and row.get("status") in skip_statuses)


def read_existing_rows(path: Path) -> dict[tuple[str, str], dict[str, Any]]:
    rows: dict[tuple[str, str], dict[str, Any]] = {}
    if not path.exists():
        return rows
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            payload = json.loads(line)
            if isinstance(payload, dict) and not payload.get("summary") and isinstance(payload.get("variant"), dict):
                budget = payload.get("budget_name")
                name = payload["variant"].get("name")
                if isinstance(budget, str) and isinstance(name, str):
                    rows[(budget, name)] = payload
    return rows


def append_jsonl(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(payload, ensure_ascii=False, sort_keys=True))
        handle.write("\n")


def default_schema() -> dict[str, Any]:
    note_item = {
        "type": "object",
        "additionalProperties": False,
        "required": ["candidate_id", "note", "reason"],
        "properties": {"candidate_id": {"type": "string"}, "note": {"type": "string"}, "reason": {"type": "string"}},
    }
    return {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "decisions",
            "people_updates",
            "profile_notes",
            "rollout_friction_notes",
            "local_llm_notes",
            "repo_specific_notes",
            "discard_reasons",
            "reviewed_candidate_ids",
        ],
        "properties": {
            "decisions": {"type": "array", "items": decision_item()},
            "people_updates": {"type": "array", "items": note_item},
            "profile_notes": {"type": "array", "items": note_item},
            "rollout_friction_notes": {"type": "array", "items": note_item},
            "local_llm_notes": {"type": "array", "items": note_item},
            "repo_specific_notes": {"type": "array", "items": note_item},
            "discard_reasons": {"type": "array", "items": discard_item()},
            "reviewed_candidate_ids": {"type": "array", "items": {"type": "string"}},
        },
    }


def decision_item() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["candidate_id", "action", "destination", "reason"],
        "properties": {
            "candidate_id": {"type": "string"},
            "action": {"type": "string", "enum": ["note", "discard"]},
            "destination": {
                "type": "string",
                "enum": [
                    "people_updates",
                    "profile_notes",
                    "rollout_friction_notes",
                    "local_llm_notes",
                    "repo_specific_notes",
                    "discard_reasons",
                ],
            },
            "reason": {"type": "string"},
        },
    }


def discard_item() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["candidate_id", "reason"],
        "properties": {"candidate_id": {"type": "string"}, "reason": {"type": "string"}},
    }


def read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"{path} did not contain a JSON object")
    return payload


def compact_json(payload: object) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


if __name__ == "__main__":
    raise SystemExit(main())
